# -*- coding: utf-8 -*-
"""PineconeDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvroIGHjD0saPxe_HQWeBo3yBfJfwqvL
"""

!pip install pinecone-client -q
!pip install sentence_transformers

#Create data to add

content1="Artificial Intelligence (AI) is transforming industries worldwide, enhancing automation, decision-making, and data analysis. AI encompasses machine learning, deep learning, and neural networks, which enable systems to learn and improve from data. Applications of AI include healthcare diagnostics, fraud detection, and personalized recommendations in e-commerce."
content2="Climate change is a pressing global issue caused by greenhouse gas emissions from human activities. Rising temperatures, melting glaciers, and extreme weather events threaten ecosystems and biodiversity. Scientists advocate for renewable energy sources, carbon footprint reduction, and sustainable practices to mitigate climate change."
content3="Quantum computing is a revolutionary field that leverages quantum mechanics to perform complex computations at unprecedented speeds. Unlike classical computers, which use bits, quantum computers use qubits that exist in superposition states. Companies like Google and IBM are advancing quantum research, aiming for breakthroughs in cryptography, material science, and AI."
content4="Blockchain technology provides a decentralized and secure method for recording transactions. Initially developed for cryptocurrencies like Bitcoin, blockchain now powers applications in supply chain management, digital identity verification, and smart contracts. Its immutable and transparent nature makes it a powerful tool for reducing fraud and enhancing trust."
content5="The field of biotechnology is revolutionizing medicine, agriculture, and industry. Advances in genetic engineering, CRISPR technology, and synthetic biology enable scientists to develop new treatments for genetic disorders, enhance crop yields, and produce sustainable biofuels. Ethical considerations and regulatory policies play crucial roles in shaping the future of biotechnology."

from sentence_transformers import SentenceTransformer

embedding_model=SentenceTransformer("all-mpnet-base-v2")

encoded_contents=embedding_model.encode([content1,content2,content3,content4,content5])
encoded_contents

len(encoded_contents[0])

# Create pinecone reference with API key and spec

from pinecone import Pinecone
from pinecone import ServerlessSpec

pinecone=Pinecone(api_key="pcsk_6EqgMR_6YTMahjL5924eKq6JbUKH8kCYWFbLYEGW7xdhKrdHFP8kpJxc4nyWxZDRqFfsuQ")
spec=ServerlessSpec(cloud="aws",region="us-east-1")

#Create pinecone index

pinecone.create_index("example-index",dimension=768,metric="cosine",spec=spec)

pinecone.list_indexes()

#Use index

index=pinecone.Index("example-index")

index.describe_index_stats()

#Add data to pinecone index

index.upsert([
    {"id":"id1","values":encoded_contents[0],"metadata":{"soursce":"Technology"}},
    {"id":"id2","values":encoded_contents[1],"metadata":{"soursce":"Environment"}},
    {"id":"id3","values":encoded_contents[2],"metadata":{"soursce":"Science"}},
    {"id":"id4","values":encoded_contents[3],"metadata":{"soursce":"Finance"}},
    {"id":"id5","values":encoded_contents[4],"metadata":{"soursce":"BioTechnology"}}
])

#Similary checking

input_text=str(input())
query_encode=embedding_model.encode([input_text])
query_encode

index.query(
    vector=query_encode[0].tolist(),
    top_k=1,
    include_values=False,
    include_metadata=True
)

#Add data

content6="Cybersecurity is a critical aspect of the digital age, protecting sensitive information from cyber threats such as hacking, phishing, and ransomware attacks. Organizations implement security measures like encryption, multi-factor authentication, and AI-driven threat detection to safeguard data. With the rise of cloud computing and IoT devices, cybersecurity challenges continue to evolve, necessitating continuous advancements in security protocols."
embedding_query=embedding_model.encode(content6).tolist()
index.upsert([
    {"id":"id6","values":embedding_query,"metadata":{"soursce":"CyberSecurity"}}
])

#Read data

res=index.fetch(ids=["id6","id3"])
res

#update data

embedding_query=embedding_model.encode("This is the updated content").tolist()
index.update(id="id5",set={"values":embedding_query})

#Delete data

index.delete(ids=["id6"])